/**
 * Dynamic sitemap — /sitemap.xml
 *
 * Generated by Next.js App Router's built-in sitemap support.
 * Revalidates every hour via ISR.
 *
 * Static pages: homepage, categories, about, editorial-policy,
 *               privacy, terms, contact.
 * Dynamic pages: all published trending_topics from Supabase.
 *
 * Priority:
 *   Tier 1 → 0.9 (hottest)
 *   Tier 2 → 0.8 (trending)
 *   Tier 3 → 0.7 (emerging)
 *   Unknown tier → 0.6
 *
 * changeFrequency:
 *   Articles published within the last 24 hours → 'hourly'
 *   Older articles → 'daily'
 */

import type { MetadataRoute } from 'next';
import { getServerClient }    from '@platform/supabase';

export const revalidate = 3600; // regenerate every hour

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.PUBLICATION_DOMAIN
    ? `https://${process.env.PUBLICATION_DOMAIN}`
    : 'https://thenewslane.com');

// Static pages that should always appear in the sitemap
const STATIC_PAGES: MetadataRoute.Sitemap = [
  {
    url:              BASE_URL,
    lastModified:     new Date(),
    changeFrequency:  'hourly',
    priority:         1.0,
  },
  {
    url:              `${BASE_URL}/about`,
    changeFrequency:  'monthly',
    priority:         0.5,
  },
  {
    url:              `${BASE_URL}/editorial-policy`,
    changeFrequency:  'monthly',
    priority:         0.4,
  },
  {
    url:              `${BASE_URL}/privacy`,
    changeFrequency:  'monthly',
    priority:         0.3,
  },
  {
    url:              `${BASE_URL}/terms`,
    changeFrequency:  'monthly',
    priority:         0.3,
  },
  {
    url:              `${BASE_URL}/contact`,
    changeFrequency:  'yearly',
    priority:         0.4,
  },
];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // ── Fetch published topics ──────────────────────────────────────────────
  let articleEntries: MetadataRoute.Sitemap = [];

  try {
    const supabase = getServerClient();
    const { data, error } = await supabase
      .from('trending_topics')
      .select('slug, published_at, viral_tier')
      .eq('status', 'published')
      .eq('fact_check', 'yes')
      .not('published_at', 'is', null)
      .order('published_at', { ascending: false });

    if (error) {
      console.error('[sitemap] Supabase query failed:', error.message);
    } else {
      const now        = Date.now();
      const oneDayMs   = 24 * 60 * 60 * 1000;

      articleEntries = ((data ?? []) as {
        slug:         string;
        published_at: string;
        viral_tier:   1 | 2 | 3 | null;
      }[]).map(topic => {
        const publishedAt  = new Date(topic.published_at);
        const ageMs        = now - publishedAt.getTime();
        const isRecent     = ageMs < oneDayMs;

        const priority =
          topic.viral_tier === 1 ? 0.9 :
          topic.viral_tier === 2 ? 0.8 :
          topic.viral_tier === 3 ? 0.7 : 0.6;

        return {
          url:             `${BASE_URL}/trending/${topic.slug}`,
          lastModified:    publishedAt,
          changeFrequency: (isRecent ? 'hourly' : 'daily') as MetadataRoute.Sitemap[number]['changeFrequency'],
          priority,
        };
      });
    }
  } catch (err) {
    // Build-time: SUPABASE env vars absent — return static pages only
    console.warn('[sitemap] Skipping Supabase fetch:', (err as Error).message);
  }

  return [...STATIC_PAGES, ...articleEntries];
}
