#!/usr/bin/env python3
"""
Check the actual database schema vs what the code expects.
"""

import sys
sys.path.insert(0, '.')

def main():
    """Check database schema."""
    print("🔍 Checking database schema...")
    print("=" * 60)
    
    try:
        from utils.supabase_client import db
        
        print("📊 Actual trending_topics table schema:")
        try:
            # Get a sample record to see what columns exist
            result = db.client.table("trending_topics").select("*").limit(1).execute()
            
            if result.data and len(result.data) > 0:
                sample_record = result.data[0]
                print("   Columns in database:")
                for column, value in sorted(sample_record.items()):
                    value_type = type(value).__name__ if value is not None else "null"
                    value_preview = str(value)[:50] + "..." if value and len(str(value)) > 50 else str(value)
                    print(f"     {column}: {value_type} = {value_preview}")
            else:
                print("   ❌ No records found to inspect schema")
        except Exception as e:
            print(f"   ❌ Schema inspection failed: {e}")
        
        print("\n📝 What the new content generation code expects:")
        print("   Fields generated by content_generation_node.py:")
        expected_fields = [
            "seo_title",
            "meta_description", 
            "summary_16w",
            "article_50w",
            "faq",
            "facebook_post",
            "instagram_caption",
            "twitter_thread",
            "youtube_script",
            "image_prompt",
            "iab_categories",
            "slug"
        ]
        for field in expected_fields:
            print(f"     {field}")
        
        print("\n📋 What publish node maps to database:")
        print("   From graph.py _node_publish():")
        mapping = {
            "summary_16w": "summary (column)",
            "article_50w": "article (column)", 
            "seo_title": "schema_blocks JSONB",
            "meta_description": "schema_blocks JSONB",
            "faq": "schema_blocks JSONB",
            "facebook_post": "social_copy JSONB",
            "instagram_caption": "social_copy JSONB",
            "twitter_thread": "social_copy JSONB",
            "youtube_script": "social_copy JSONB",
            "image_prompt": "schema_blocks JSONB"
        }
        for field, db_location in mapping.items():
            print(f"     {field} → {db_location}")
        
        print("\n🔍 Testing actual field access...")
        try:
            # Try to access the fields that should contain content
            result = db.client.table("trending_topics").select(
                "id, title, summary, article, schema_blocks, social_copy, status"
            ).eq("status", "published").limit(3).execute()
            
            if result.data:
                print("   Sample published records:")
                for i, record in enumerate(result.data, 1):
                    title = (record.get("title") or "NULL")[:30]
                    summary = "✓" if record.get("summary") else "NULL"
                    article = "✓" if record.get("article") else "NULL"
                    schema_blocks = "✓" if record.get("schema_blocks") else "NULL"
                    social_copy = "✓" if record.get("social_copy") else "NULL"
                    
                    print(f"     {i}. '{title}' summary={summary} article={article} schema_blocks={schema_blocks} social_copy={social_copy}")
                
                # Check if content is actually there
                content_count = sum(1 for r in result.data if r.get("summary") and r.get("article"))
                if content_count > 0:
                    print(f"   ✅ {content_count}/3 published topics have summary+article content")
                    print("   🎉 This means content SHOULD be appearing on your website!")
                    print("      If not, check your web app code or deployment")
                else:
                    print("   ❌ Published topics don't have content in summary/article fields")
                    print("      This indicates the publish step isn't working correctly")
            else:
                print("   ❌ No published records found")
        except Exception as e:
            print(f"   ❌ Field access test failed: {e}")
        
        return True
        
    except Exception as e:
        print(f"❌ Schema check failed: {e}")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)